# Generated by Django 4.1.7 on 2023-05-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
    ]
