# Generated by Django 4.1.7 on 2023-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_lang_answer_alter_lang_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='color',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='body',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lang',
            name='prompt',
            field=models.TextField(max_length=500),
        ),
    ]
