# Generated by Django 4.1.7 on 2023-05-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_datamodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='color',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=20),
        ),
    ]
