# Generated by Django 4.1.7 on 2023-05-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_datamodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='color',
            field=models.CharField(choices=[('bg-info', 'Low'), ('bg-success', 'Medium'), ('bg-danger', 'High')], default='bg-success', max_length=20),
        ),
    ]
